#!/bin/bash
#SBATCH --job-name=a-PCA1-GWAS_admix
#SBATCH --account=om62
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --mem-per-cpu=10G
#SBATCH --time=09:00:00
#SBATCH --output=a-PCA1_GWAS-admix-%a.out
#SBATCH --error=a-PCA1_GWAS-admix-%a.err
#SBATCH --array=1-113

# Navigate to the working directory
cd ~/ha22_scratch/edta-ragweed/pcangsd

# Get the task ID
N=$SLURM_ARRAY_TASK_ID

# Read the window information from the list
WIND=$(cat windows-chrs-only-10Mb.list | head -n $N | tail -n 1 | awk '{print $1 ":" $2 "-" $3}')

# Load necessary modules
module load nixpkgs
module load intel
module load angsd/2024-02-07 

# Create the output directory if it doesn't exist
mkdir -p angsd_GWAS
# Execute the angsd command with the specified parameters
angsd \
  -nThreads 8 \
  -bam bamlist-modern_GWAS_225.txt \
  -r $WIND \
  -out angsd_GWAS/PCA-admix-$N \
  -GL 2 \
  -doMajorMinor 1 \
  -doCounts 1 \
  -doGLF 2 \
  -SNP_pval 1e-6 \
  -doMaf 2 \
  -doGeno -1 \
  -doPost 1 \
  -minMapQ 30 \
  -minQ 20 \
  -trim 5 \
  -minMaf 0.05 \
  -minInd 225 \
  -geno_minDepth 2 \
  -setMinDepthInd 2 \
  -uniqueOnly 1 \
  -doPlink 2

  # LD filter with plink

#!/bin/bash
#SBATCH --job-name=a-PCA_plink
#SBATCH --account=om62
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --mem-per-cpu=10G
#SBATCH --time=06:00:00
#SBATCH --output=a-PCA_plink-%a.out
#SBATCH --error=a-PCA_plink-%a.err
#SBATCH --array=1-113

cd ~/ha22_scratch/edta-ragweed/pcangsd

N=$SLURM_ARRAY_TASK_ID

module load plink/1.9 

# LD filter with plink
plink \
--tfile angsd_GWAS/PCA-admix-$N \
--allow-extra-chr \
--indep-pairwise 50 5 0.5 \
--out angsd_GWAS/PCA-admix-$N

# clean up ((base) [bnongtho@m3-login3 pcangsd]$ nano bedfiles_pcasites_nogenes_mod_GWAS.sh))
#!/bin/bash
#SBATCH --job-name=PCAbed_mod_GWAS-admix
#SBATCH --account=om62
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --mem-per-cpu=10G
#SBATCH --time=03:00:00
#SBATCH --output=PCAbed_mod_GWAS-admix-%a.out
#SBATCH --error=PCAbed_mod_GWAS-admix-%a.err


# Loop over all 113 files and append the processed output to PCA-admix.bed
for N in {1..113}
do
    zcat angsd_GWAS/PCA-admix-$N.mafs.gz | awk '{print $1 "\t" $2 "\t" $2}' | tail -n +2
done > angsd_GWAS/PCA_mod_GWAS-admix.bed

module load StdEnv/2020
module load bedtools/2.30.0

# Use bedtools to find regions in PCA-admix.bed that do not overlap with genes in genes.bed
bedtools intersect -a angsd_GWAS/PCA_mod_GWAS-admix.bed -b genes.bed -v | awk -F "\t" '{print $1 "_" $2}' > angsd_GWAS/PCA_mod_GWAS-admix.nogenes.txt


# prune-remove_mod_GWAS-genes.R
library(data.table)

setwd("~/ha22_scratch/edta-ragweed/pcangsd/angsd_GWAS")

N = commandArgs(trailingOnly = TRUE)[1]

# read in beagle file
beagle = fread(paste0("PCA-admix-", N, ".beagle.gz"), header = T)

# read in LD prune list
prune.in = scan(paste0("PCA-admix-", N, ".prune.in"), what = 'list')

# prune beagle file for LD
beagle.pruned = beagle[which(beagle$marker %in% prune.in), ]

# read in gene filter list
nogenes = scan("~/ha22_scratch/edta-ragweed/pcangsd/angsd_GWAS/PCA_mod_GWAS-admix.nogenes.txtt", what = 'list')

# apply gene filter
beagle.pruned.nogenes = beagle.pruned[which(beagle.pruned$marker %in% nogenes), ]


# write out pruned and filtered beagle file
fwrite(beagle.pruned.nogenes, file = paste0("PCA-admix-", N, ".pruned.nogenes.beagle.gz"),
    col.names = F, row.names = F, quote = F, sep = "\t", compress = "gzip", nThread = 36)

# prune-remove_mod_GWAS-genes-PCA-admix.sh
#!/bin/bash
#SBATCH --job-name=prune-remove_GWAS-genes-PCA-admix
#SBATCH --account=om62
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=36
#SBATCH --time=03:00:00
#SBATCH --output=prune-remove_GWAS-genes-PCA-admix.out
#SBATCH --error=prune-remove_GWAS-genes-PCA-admix.err

module load R

cd ~/ha22_scratch/edta-ragweed/pcangsd/angsd_GWAS

for N in {1..113}; do Rscript prune-remove_mod_GWAS-genes.R $N; done

###

# concatenate filtered beagle files and downsample to 100k sites

#!/bin/bash

for N in {1..113}; do zcat PCA-admix-$N.pruned.nogenes.beagle.gz; done \
| shuf -n 100000 | gzip > PCA-admix.pruned.nogenes.mod.GWAS.100k.beagle.gz

# run PCAngsd
pcangsd -t 8 -b PCA-admix.pruned.nogenes.mod.GWAS.100k.beagle.gz -o PCA-admix.mod.GWAS.pruned.nogenes.100k
